title: Algebra314
description: A mathematics blog exploring ideas from first principles.
url: "https://www.algebra314.com"
baseurl: ""
theme: minima
header_pages:
  - about.md
minima:
  social_links: []
author:
  name: Berkay
